// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity ^0.8.25;

// THIS FILE IS AUTOGENERATED BY THE BUILD SCRIPT. DO NOT EDIT BY HAND.

import {DeploySuite} from "../abstract/RainDeploySuitesBase.sol";

import {LibRainlangParserReleased} from "./LibRainlangParserReleased.sol";

import {LibRainlangStoreReleased} from "./LibRainlangStoreReleased.sol";

import {LibRainlangInterpreterReleased} from "./LibRainlangInterpreterReleased.sol";

import {LibRainlangExpressionDeployerReleased} from "./LibRainlangExpressionDeployerReleased.sol";

import {LibRainlangReleased} from "./LibRainlangReleased.sol";

/// @title LibReleasedSuites
/// @notice Every frozen release this repo has cut, of every contract it
/// deploys: the per-contract released libs concatenated, in declaration
/// order.
///
/// There is one released lib per deployed contract because a release freezes
/// every contract it names into a single tag directory, so a lib that took
/// the record whole would give another contract's snapshot this contract's
/// suite key and collide with its own entry for that tag. This is where
/// those libs meet, and it is emitted from the same list that wrote them --
/// so a contract that is generated, aliased and frozen cannot be missing
/// from the declaration, and a release missing from the declaration is a
/// release every check quietly stops asking about.
library LibReleasedSuites {
    /// Every released suite, in declaration order.
    /// @return The released suites.
    function releasedSuites() internal pure returns (DeploySuite[] memory) {
        DeploySuite[][] memory released = new DeploySuite[][](5);
        released[0] = LibRainlangParserReleased.releasedSuites();
        released[1] = LibRainlangStoreReleased.releasedSuites();
        released[2] = LibRainlangInterpreterReleased.releasedSuites();
        released[3] = LibRainlangExpressionDeployerReleased.releasedSuites();
        released[4] = LibRainlangReleased.releasedSuites();

        uint256 total = 0;
        for (uint256 i = 0; i < released.length; i++) {
            total += released[i].length;
        }

        DeploySuite[] memory suites = new DeploySuite[](total);

        uint256 offset = 0;
        for (uint256 i = 0; i < released.length; i++) {
            for (uint256 j = 0; j < released[i].length; j++) {
                suites[offset + j] = released[i][j];
            }
            offset += released[i].length;
        }

        return suites;
    }
}
