// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity ^0.8.25;

// THIS FILE IS AUTOGENERATED BY THE BUILD SCRIPT. DO NOT EDIT BY HAND.

import {DeploySuite} from "../abstract/RainDeploySuitesBase.sol";

import {
    DEPLOYED_ADDRESS as RainlangParser_0_1_9_DEPLOYED_ADDRESS,
    BYTECODE_HASH as RainlangParser_0_1_9_BYTECODE_HASH,
    CREATION_CODE as RainlangParser_0_1_9_CREATION_CODE,
    RUNTIME_CODE as RainlangParser_0_1_9_RUNTIME_CODE,
    DEPENDENCIES as RainlangParser_0_1_9_DEPENDENCIES
} from "../generated/0_1_9/RainlangParser.sol";

/// @title LibRainlangParserReleased
/// @notice Every frozen release of `RainlangParser`: one entry per file in
/// the append-only `src/generated/<tag>/` record, in tag order.
///
/// The deploy address, code hash, creation code, runtime code and dependency
/// list of each entry are aliased from that release's own frozen snapshot, so
/// what a release deployed, and what it required to already be on chain, are
/// read from the immutable file and from nowhere else. A dependency dropped
/// from current source stays required by the releases cut with it, and one
/// added is not imposed on releases cut without it.
///
/// The key and the artifact path are explorer and ordering metadata
/// regenerated from the CURRENT declaration, and are not part of that
/// record. A moved source path retroactively updates every entry's artifact
/// path, which is intended: the alternative is parsing this generated file
/// back in to preserve what it last said.
library LibRainlangParserReleased {
    /// Every frozen release, in tag order.
    /// @return The released suites.
    function releasedSuites() internal pure returns (DeploySuite[] memory) {
        DeploySuite[] memory suites = new DeploySuite[](1);
        suites[0] = DeploySuite({
            suite: "parser@0_1_9",
            creationCode: RainlangParser_0_1_9_CREATION_CODE,
            storedDeployedAddress: RainlangParser_0_1_9_DEPLOYED_ADDRESS,
            storedBytecodeHash: RainlangParser_0_1_9_BYTECODE_HASH,
            storedRuntimeCode: RainlangParser_0_1_9_RUNTIME_CODE,
            artifactPath: "src/concrete/RainlangParser.sol:RainlangParser",
            dependencies: abi.decode(RainlangParser_0_1_9_DEPENDENCIES, (address[]))
        });
        return suites;
    }
}
