[package]
name = "rain-interpreter-env"
version = "0.0.0"
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
once_cell = { workspace = true }
alloy = { workspace = true }
