[profile.default]
src = 'src'
out = 'out'
libs = ['dependencies']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

solc = "0.8.25"
evm_version = "cancun"

# Try to make sure the optimizer doesn't touch the output in a way that can break
# source maps for debugging.
# via_ir = true
# optimizer = false
# optimizer_runs = 0
# optimizer_steps = 0

# These settings should be used for snapshots
optimizer = true
optimizer_runs = 1000000

ffi = true
bytecode_hash = "none"
cbor_metadata = false

fs_permissions = [
  { access = "read-write", path = "./out/test/" },
  { access = "read-write", path = "./meta" },
  { access = "read-write", path = "src/generated" },
  { access = "read-write", path = "./crates/bindings/abi" },
  { access = "read-write", path = "./crates/test_fixtures/abi" },
  { access = "read", path = "./out" },
  { access = "write", path = "./deployments/latest/RainlangParser" },
  { access = "write", path = "./deployments/latest/RainlangStore" },
  { access = "write", path = "./deployments/latest/RainlangInterpreter" },
  { access = "write", path = "./deployments/latest/RainlangExpressionDeployer" },
]

gas_limit = "18446744073709551615"

[dependencies]
forge-std = "1.16.1"
"@openzeppelin-contracts" = "5.6.1"
"rain-datacontract" = "0.1.0"
"rain-deploy" = "0.1.3"
"rain-extrospection" = "0.1.1"
"rain-interpreter-interface" = "0.1.0"
"rain-intorastring" = "0.1.0"
"rain-lib-hash" = "0.1.0"
"rain-lib-memkv" = "0.1.0"
"rain-lib-typecast" = "0.1.0"
"rain-math-binary" = "0.1.1"
"rain-math-float" = "0.1.1"
"rain-metadata" = "0.1.0"
"rain-sol-codegen" = "0.1.0"
"rain-solmem" = "0.1.3"
"rain-string" = "0.2.0"
"rain-tofu-erc20-decimals" = "0.1.1"

[soldeer]
recursive_deps = false

[fuzz]
runs = 2048

[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC_URL}"
base = "${BASE_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
flare = "${FLARE_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"

[etherscan]
arbitrum = { key = "${CI_DEPLOY_ARBITRUM_ETHERSCAN_API_KEY}" }
base = { key = "${CI_DEPLOY_BASE_ETHERSCAN_API_KEY}" }
base_sepolia = { key = "${CI_DEPLOY_BASE_SEPOLIA_ETHERSCAN_API_KEY}" }
flare = { key = "${CI_DEPLOY_FLARE_ETHERSCAN_API_KEY}" }
polygon = { key = "${CI_DEPLOY_POLYGON_ETHERSCAN_API_KEY}" }
