// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity =0.8.25;

import {Test} from "forge-std-1.16.1/src/Test.sol";
import {RainlangReferenceExtern} from "../../../src/concrete/extern/RainlangReferenceExtern.sol";
import {LibExtrospectBytecode} from "rain-extrospection-0.1.14/src/lib/LibExtrospectBytecode.sol";
import {LibExtrospectMetamorphic} from "rain-extrospection-0.1.14/src/lib/LibExtrospectMetamorphic.sol";
import {
    BYTECODE_HASH as REFERENCE_EXTERN_BYTECODE_HASH
} from "../../../src/generated/RainlangReferenceExternPointers.sol";

/// @title RainlangReferenceExternBytecodeTest
/// @notice The bytecode properties of the reference extern that the generated
/// pointers file is keyed to. Nothing here is a deploy record: the extern is a
/// reference implementation, never a deploy candidate, so its generated
/// `BYTECODE_HASH` is the only thing that makes its pointers file
/// stale-detectable.
contract RainlangReferenceExternBytecodeTest is Test {
    /// ReferenceExtern bytecode MUST NOT contain Solidity CBOR metadata.
    function testNoCborMetadataReferenceExtern() external {
        RainlangReferenceExtern extern = new RainlangReferenceExtern();
        assertFalse(
            LibExtrospectBytecode.tryTrimSolidityCBORMetadata(address(extern).code),
            "ReferenceExtern bytecode contains CBOR metadata"
        );
    }

    /// ReferenceExtern bytecode MUST NOT contain reachable metamorphic risk
    /// opcodes.
    function testNotMetamorphicReferenceExtern() external {
        RainlangReferenceExtern extern = new RainlangReferenceExtern();
        LibExtrospectMetamorphic.checkNotMetamorphic(address(extern).code);
    }

    /// The reference extern's generated bytecode hash MUST be the hash of the
    /// bytecode current source produces.
    function testReferenceExternBytecodeHash() external {
        RainlangReferenceExtern extern = new RainlangReferenceExtern();
        assertEq(keccak256(address(extern).code), REFERENCE_EXTERN_BYTECODE_HASH);
    }
}
