[package]
name = "rain_interpreter_eval"
version = "0.1.0"
edition.workspace = true
license.workspace = true
homepage.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = { workspace = true }
alloy-primitives = {workspace = true}
rain_interpreter_bindings = { workspace = true }
alloy-sol-types = { workspace = true }
