name: Git is clean
on: [push]

jobs:
  git-clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true
      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          # restore and save a cache using this key
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          # if there's no cache hit, restore a cache by this prefix
          restore-prefixes-first-match: nix-${{ runner.os }}-
          # collect garbage until the Nix store size (in bytes) is at most this number
          # before trying to save a new cache
          # 1G = 1073741824
          gc-max-store-size-linux: 1G

      # Build metas etc. required to do a correct pointer build.
      - run: nix develop -c i9r-prelude

      - run: nix develop -c forge script ./script/BuildPointers.sol

      # Format the repo after generating pointers so that the pointer files are
      # formatted too.
      - run: nix develop -c forge fmt

      # Check if the repo is clean after generating pointers and formatting.
      - run: git diff --exit-code