name: Git is clean
on: [push]

jobs:
  git-clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      # Build metas etc. required to do a correct pointer build.
      - run: nix develop -c i9r-prelude

      - run: nix develop -c forge script ./script/BuildPointers.sol

      # Format the repo after generating pointers so that the pointer files are
      # formatted too.
      - run: nix develop -c forge fmt

      # Check if the repo is clean after generating pointers and formatting.
      - run: git diff --exit-code