name: Git is clean
on: [push]

jobs:
  git-clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - run: nix develop -c forge script ./script/BuildAuthoringMeta.sol
      - run: nix develop -c forge script ./script/BuildPointers.sol

      - run: git diff --exit-code