name: GitHub PR Size Assessment
on:
  pull_request:
    types:
      - closed

jobs:
  assess-pr-size-on-merge:
    uses: rainlanguage/github-chore/.github/workflows/pr-assessment.yml@main
    with:
      pr_number: ${{ github.event.pull_request.number }}
      repo: ${{ github.event.repository.name }}
      owner: ${{ github.repository_owner }}
      merged: ${{ github.event.pull_request.merged }}
